
#pragma once
#include "NativeGameplayTags.h"

namespace CombatTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Bullet);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Explosive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Melee);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fall);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_ZoneDOT);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Head);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Torso);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Arm);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Leg);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Material_Flesh);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Material_Metal);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Material_Wood);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Material_Concrete);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_FireMode_Single);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_FireMode_Burst);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_FireMode_Auto);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Action_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Action_ReloadBegin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Action_ReloadEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Action_EquipBegin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Action_EquipEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Recoil_Profile_Default);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Recoil_Profile_AR_Basic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Recoil_Profile_SMG_Basic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Recoil_Profile_SR_Basic);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spread_Pattern_Default);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spread_Pattern_Shotgun_Pellet);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spread_Pattern_SMG_Spray);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FX_Hitmarker_On);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FX_MuzzleFlash_On);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FX_Tracer_On);
}
